// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlShortener.Data;

#nullable disable

namespace UrlShortener.Data.Migrations
{
    [DbContext(typeof(UrlDbContext))]
    partial class UrlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UrlShortener.Data.Models.UrlDb", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClicksCount")
                        .HasColumnType("int");

                    b.Property<string>("Created")
                        .HasColumnType("longtext");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Urls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClicksCount = 0,
                            Created = "26.09.2023 15:15:20",
                            LongUrl = "https://metanit.com",
                            ShortUrl = "short.by/YFn1g4"
                        },
                        new
                        {
                            Id = 2,
                            ClicksCount = 0,
                            Created = "26.09.2023 15:15:20",
                            LongUrl = "https://learn.javascript.ru",
                            ShortUrl = "short.by/IFkSo1"
                        },
                        new
                        {
                            Id = 3,
                            ClicksCount = 0,
                            Created = "26.09.2023 15:15:20",
                            LongUrl = "https://rabota.by",
                            ShortUrl = "short.by/GTof2r"
                        },
                        new
                        {
                            Id = 4,
                            ClicksCount = 0,
                            Created = "26.09.2023 15:15:20",
                            LongUrl = "https://ru.legacy.reactjs.org",
                            ShortUrl = "short.by/Ar2Tyk"
                        },
                        new
                        {
                            Id = 5,
                            ClicksCount = 0,
                            Created = "26.09.2023 15:15:20",
                            LongUrl = "https://hub.docker.com/search?q=mysql&type=image",
                            ShortUrl = "short.by/of4I8g"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
